var data = [
    {
        "id": 1,
        "category": "iphone",
        "name": "iPhone 12 Max Pro",
        "rating": 4.3,
        "image": "https://rukminim1.flixcart.com/image/312/312/kg8avm80/mobile/g/n/w/apple-iphone-12-pro-max-dummyapplefsn-original-imafwgcyhmehwy2z.jpeg?q=70",
        "available": true,
        "condition": "new",
        "color": "Gold",
        "price": "$1000",
        "keywords": ["gold","iphone 12 max pro","iphone series","latest iphone", "apple iphone 12 max pro"],
        "discount": 0
    },
    {
        "id": 2,
        "category": "watch",
        "name": "Apple Watch Series 3 GPS",
        "rating": 3.8,
        "image": "https://rukminim1.flixcart.com/image/312/312/jmi22kw0/smartwatch/y/d/j/mtf32hn-a-apple-original-imaf9ec8ssmfcuxf.jpeg?q=70",
        "available": true,
        "condition": "new",
        "color": "Black",
        "price": "$300",
        "keywords": ["watches","black","apple watch", "watch series 3", "apple watch series","apple watch series 3 gps", "apple watch under 600"],
        "discount": 0
    },
    {
        "id": 3,
        "category": "Airpod",
        "name": "Apple Airpods",
        "rating": 4.5,
        "image": "https://rukminim1.flixcart.com/image/612/612/k1pbpu80pkrrdj/headphone/h/u/t/apple-mv7n2hn-a-original-imaff78z59efb54q.jpeg?q=70",
        "available": true,
        "condition": "new",
        "color": "White",
        "price": "$250",
        "keywords": ["white","airpods", "apple airdrops","apple earphone"],
        "discount": 0
    },
    {
        "id": 4,
        "category": "speaker",
        "name": "Apple Homepod",
        "rating": 4.1,
        "image": "https://rukminim1.flixcart.com/image/612/612/kh2b4i80/smart-assistant/t/z/m/homepod-mini-my5h2hn-a-apple-original-imafx5vzjxkzu9y8.jpeg?q=70",
        "available": true,
        "condition": "new",
        "color": "White",
        "price": "$140",
        "keywords": ["white","apple speaker", "apple speakers","speaker","speaker"],
        "discount": 0
    },

    {
        "id": 5,
        "category": "speaker",
        "name": "Apple Homepod",
        "rating": 4.1,
        "image": "https://rukminim1.flixcart.com/image/612/612/kh2b4i80/smart-assistant/u/d/e/homepod-mini-my5g2hn-a-apple-original-imafx5vzp3buhqgd.jpeg?q=70",
        "available": true,
        "condition": "new",
        "color": "Black",
        "price": "$137",
        "keywords": ["black","apple speaker", "apple speakers","speaker","speaker"],
        "discount": 0
    },
    {
        "id": 6,
        "category": "iPhone",
        "name": "iPhone 12 mini",
        "rating": 3.9,
        "image": "https://rukminim1.flixcart.com/image/312/312/kg8avm80/mobile/r/2/r/apple-iphone-12-mini-dummyapplefsn-original-imafwgbfcswp9fh5.jpeg?q=70",
        "available": true,
        "condition": "new",
        "color": "Black",
        "price": "$800",
        "keywords": ["black","iphone mini","iphone", "iphone 12 mini"],
        "discount": 0
    },
    {
        "id": 7,
        "category": "iPhone",
        "name": "iPhone 12 mini",
        "rating": 4.6,
        "image": "https://rukminim1.flixcart.com/image/312/312/kg8avm80/mobile/d/g/b/apple-iphone-12-mini-dummyapplefsn-original-imafwgbfhfevaajh.jpeg?q=70",
        "available": true,
        "condition": "new",
        "color": "White",
        "price": "$801",
        "keywords": ["white","iphone mini","iphone", "iphone 12 mini"],
        "discount": 0
    },
    {
        "id": 8,
        "category": "speaker",
        "name": "Apple Homepod Smart Speaker",
        "rating": 4.1,
        "image": "https://www.reliancedigital.in/medias/Apple-HomePod-Smart-Speaker-Space-Grey-491630602-i-1-1200Wx1200H?context=bWFzdGVyfGltYWdlc3w1MTkwNDh8aW1hZ2UvanBlZ3xpbWFnZXMvaDZlL2g3Yy85MjkwNDQzMjkyNzAyLmpwZ3w2YzQxNzkxYzY5OTIxNzQwOGMyODY5NDQ3MWRhMWZjNzk2OGExNTdlYmU3YjhjY2JkNjY4YzRjMTJjNTM3NzAz",
        "available": true,
        "condition": "new",
        "color": "Black",
        "price": "$271",
        "keywords": ["black","Apple homepod smart speaker","mini speaker", "speaker", "apple speaker", "homepod mini speaker"],
        "discount": 0
    },

    {
        "id": 9,
        "category": "watch",
        "name": "Apple Watch Series 3 GPS",
        "rating": 3.8,
        "image": "https://rukminim1.flixcart.com/image/312/312/jmi22kw0/smartwatch/y/r/m/mtey2hn-a-apple-original-imaf9ec8nvqu6ymc.jpeg?q=70",
        "available": true,
        "condition": "new",
        "color": "White",
        "price": "$287",
        "keywords": ["watches","white","apple watch", "watch series 3", "apple watch series", "apple watch series 3 gps", "apple watch under 600"],
        "discount": 0
    },
    {
        "id": 10,
        "category": "Airpod",
        "name": "Apple Airpods Pro WIreless",
        "rating": 4.5,
        "image": "https://rukminim1.flixcart.com/image/612/612/k5cs87k0/headphone/h/8/8/apple-earphone-1a-original-imafmyz2ufupkvxr.jpeg?q=70",
        "available": true,
        "condition": "new",
        "color": "White",
        "price": "$327",
        "keywords": ["white","apple airpods pro wireless","latest airpods","airpods", "apple airdrops","apple earphone"],
        "discount": 0
    },
    {
        "id": 11,
        "category": "iphone",
        "name": "Apple iPhone XR",
        "rating": 4.3,
        "image": "https://rukminim1.flixcart.com/image/312/312/k0lbdzk0pkrrdj/mobile/s/p/d/apple-iphone-xr-mry42hn-a-original-imafbhyxurw8y7zg.jpeg?q=70",
        "available": true,
        "condition": "new",
        "color": "Black",
        "price": "$570",
        "keywords": ["black","iphone xr black","apple iphone xr", "iphone", "iphone series","latest iphone"],
        "discount": 0
    },

    {
        "id": 12,
        "category": "iphone",
        "name": "Apple iPhone 11",
        "rating": 4.6,
        "image": "https://rukminim1.flixcart.com/image/612/612/kgiaykw0/mobile/y/n/y/apple-iphone-11-mhda3hn-a-original-imafwqepdb3fxtug.jpeg?q=70",
        "available": true,
        "condition": "new",
        "color": "Black",
        "price": "$582",
        "keywords": ["black","iphone 11 black","apple iphone 11 black", "iphone", "iphone series","latest iphone"],
        "discount": 0
    },

    {
        "id": 13,
        "category": "iphone",
        "name": "Apple iPhone 12",
        "rating": 4.6,
        "image": "https://rukminim1.flixcart.com/image/612/612/kg8avm80/mobile/j/f/9/apple-iphone-12-dummyapplefsn-original-imafwg8dkyh2zgrh.jpeg?q=70",
        "available": true,
        "condition": "new",
        "color": "White",
        "price": "$1094",
        "keywords": ["white","iphone 12 white 64GB","iphone 12 white","apple iphone 12 white", "iphone", "iphone series","latest iphone"],
        "discount": 0
    },

    {
        "id": 14,
        "category": "iphone",
        "name": "Apple iPhone 12",
        "rating": 4.6,
        "image": "https://rukminim1.flixcart.com/image/612/612/kg8avm80/mobile/q/8/f/apple-iphone-12-dummyapplefsn-original-imafwg8drqaam5vu.jpeg?q=70",
        "available": true,
        "condition": "new",
        "color": "Red",
        "price": "$1092",
        "keywords": ["red","iphone 12 red 64GB","iphone 12 red","apple iphone 12 red", "iphone", "iphone series","latest iphone"],
        "discount": 0
    },

    {
        "id": 15,
        "category": "iphone",
        "name": "Apple iPhone 11 Pro",
        "rating": 4.6,
        "image": "https://rukminim1.flixcart.com/image/612/612/k2jbyq80pkrrdj/mobile-refurbished/z/a/f/iphone-11-pro-max-256-u-mwhm2hn-a-apple-0-original-imafkg2ftc5cze5n.jpeg?q=70",
        "available": true,
        "condition": "new",
        "color": "Black",
        "price": "$1092",
        "keywords": ["black","iphone 11 pro red 64GB","iphone 11 pro red","apple iphone 11 pro red", "iphone", "iphone series","latest iphone"],
        "discount": 0
    },
];
